// Generates the Pucar token layer and injects it into app/globals.css between markers.
// Run with: pnpm tokens   (tsx lib/tokens/build-css.ts)
// Single source of truth: tokens.ts (decisions) + ramps.ts (primitives).
// Injected in-place (not @import) because Tailwind v4 doesn't reliably inline relative CSS imports.
//
// The generated block includes the @theme type-scale + elevation section, so TYPE/SHADOWS
// in tokens.ts actually drive the utilities (text-title-l, shadow-raised, …) — don't
// hand-author them in globals.css.

import { readFileSync, writeFileSync } from "node:fs"
import { ramps } from "./ramps"
import {
  FAMILY_RAMP,
  SOLIDS,
  BRAND_ACCENT,
  BRAND_TINT_FOREGROUND,
  SOLID_FOREGROUND,
  SURFACE_SUNKEN,
  SEMANTIC_REFS,
  SOLID_FOREGROUND_TOKENS,
  CHART_PALETTE,
  FONTS,
  RADIUS,
  TYPE,
  SHADOWS,
  NEUTRAL,
} from "./tokens"

type Theme = "light" | "dark"

// ── Guard: a semantic token must never reference itself (cyclic var() = invalid CSS).
// This exact bug shipped once (brand-accent); fail the build instead of shipping it again.
for (const [k, v] of Object.entries(SEMANTIC_REFS)) {
  if (v.includes(`var(--${k})`)) {
    throw new Error(`Cycle: SEMANTIC_REFS["${k}"] references var(--${k}) — self-referential custom properties are invalid CSS.`)
  }
}

function primitiveLines(theme: Theme): string[] {
  const out: string[] = []
  for (const [role, rampName] of Object.entries(FAMILY_RAMP)) {
    ramps[rampName][theme].forEach((hex, i) => out.push(`  --${role}-${i + 1}: ${hex};`))
  }
  out.push(`  --brand-solid: ${SOLIDS.brand[theme]};`)
  out.push(`  --success-solid: ${SOLIDS.success[theme]};`)
  out.push(`  --info-solid: ${SOLIDS.info[theme]};`)
  out.push(`  --destructive-solid: ${SOLIDS.destructive[theme]};`)
  out.push(`  --brand-accent: ${BRAND_ACCENT};`)
  out.push(`  --brand-tint-foreground: ${BRAND_TINT_FOREGROUND[theme]};`) // engineered teal text on brand-3 (selection pair)
  out.push(`  --surface-sunken: ${SURFACE_SUNKEN[theme]};`) // tuned per-theme nested-surface fill (between neutral-2 and 3)
  CHART_PALETTE[theme].forEach((hex, i) => out.push(`  --chart-${i + 1}: ${hex};`))
  return out
}

function semanticLines(): string[] {
  return Object.entries(SEMANTIC_REFS).map(([k, v]) => `  --${k}: ${v};`)
}

function foregroundLines(theme: Theme): string[] {
  const ink = SOLID_FOREGROUND[theme]
  return SOLID_FOREGROUND_TOKENS.map((t) => `  --${t}: ${ink};`)
}

function scaleLines(): string[] {
  return [
    `  --font-sans: ${FONTS.sans};`,
    `  --font-mono: ${FONTS.mono};`,
    `  --font-heading: ${FONTS.heading};`,
    `  --radius: ${RADIUS};`,
  ]
}

const px = (n: number) => `${n / 16}rem`

function themeScaleLines(): string[] {
  const out: string[] = [
    "  /* Type scale — major third (1.250), base 16, 24 locked.",
    "     Weight defaults encode the ladder (no thin text). */",
  ]
  for (const [name, t] of Object.entries(TYPE)) {
    out.push(`  --text-${name}: ${px(t.size)}; /* ${t.size} */`)
    out.push(`  --text-${name}--line-height: ${px(t.line)}; /* ${t.line} */`)
    if (t.weight !== 400) out.push(`  --text-${name}--font-weight: ${t.weight};`)
  }
  out.push("")
  out.push("  /* Elevation — Flat / Raised / Overlay / Modal. Semantic depth, never decoration. */")
  for (const [name, v] of Object.entries(SHADOWS)) out.push(`  --shadow-${name}: ${v};`)
  return out
}

const START = "/* pucar-tokens:start"
const END = "/* pucar-tokens:end */"
const START_LINE = `${START} — generated by \`pnpm tokens\` (edit lib/tokens/*, then run it) */`

const block = `${START_LINE}
@theme {
${themeScaleLines().join("\n")}
}

:root {
  /* Tier 1 — primitives (light) */
${primitiveLines("light").join("\n")}

  /* Tier 2 — semantic (shadcn API, frozen names) */
${semanticLines().join("\n")}
${foregroundLines("light").join("\n")}

  /* Scales */
${scaleLines().join("\n")}
}

.dark {
  /* Tier 1 — primitives (dark) — semantic tokens above auto-flip via these */
${primitiveLines("dark").join("\n")}

  /* Foregrounds on solids flip white → ink in dark theme */
${foregroundLines("dark").join("\n")}
}
${END}`

const path = "app/globals.css"
const css = readFileSync(path, "utf8")
const startIdx = css.indexOf(START)
const endIdx = css.indexOf(END)
if (startIdx === -1 || endIdx === -1) {
  throw new Error(`Token markers not found in ${path}. Expected "${START} ... ${END}".`)
}
const next = css.slice(0, startIdx) + block + css.slice(endIdx + END.length)
writeFileSync(path, next)
console.log(`✓ Injected tokens into ${path}  (neutral: ${NEUTRAL})`)
